name: Deploy
on: push

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/file-service:latest

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem
          ssh-keyscan -H ${{ secrets.FILE_SERVICE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2.pem ubuntu@${{ secrets.FILE_SERVICE_HOST }} '
            cd ~/file-service && \
            rm -rf ~/file-service/logs && \
            rm -rf ~/file-service/uploads && \
            mkdir -p ~/file-service/logs && \
            mkdir -p ~/file-service/uploads && \
            sudo docker pull ${{ env.IMAGE_NAME }} && \
            sudo docker rm -f file-service || true && \
            sudo docker run -d --name file-service \
              -p 80:5003 \
              -p 3002:3002 \
              --env-file .env \
              -v $(pwd)/logs:/usr/src/app/logs \
              -v $(pwd)/uploads:/usr/src/app/uploads \
              --cpus=1.5 \
              --memory=1664m \
              --memory-reservation=1024m \
              --restart unless-stopped \
              ${{ env.IMAGE_NAME }}
          '
